books = [
    {
        "id": 1,
        "title": "The Great Adventure",
        "author": "John Smith",
        "publisher": "Adventure Press",
        "published_date": "2020-05-15",
        "page_count": 320,
        "language": "English",
    },
    {
        "id": 2,
        "title": "Learning Python",
        "author": "Jane Doe",
        "publisher": "Tech Books Inc.",
        "published_date": "2022-03-10",
        "page_count": 450,
        "language": "English",
    },
    {
        "id": 3,
        "title": "Mystery of the Lost City",
        "author": "Emily Davis",
        "publisher": "Mystery House",
        "published_date": "2019-08-25",
        "page_count": 280,
        "language": "English",
    },
    {
        "id": 4,
        "title": "Cooking Made Easy",
        "author": "Michael Brown",
        "publisher": "Culinary Arts",
        "published_date": "2021-12-01",
        "page_count": 150,
        "language": "English",
    },
    {
        "id": 5,
        "title": "History of the World",
        "author": "Sarah Thompson",
        "publisher": "History Publishers",
        "published_date": "2018-07-19",
        "page_count": 500,
        "language": "English",
    },
]
