"""add user_id foreignkey to books

Revision ID: 9b0a95e82045
Revises: 362e0db184c8
Create Date: 2025-01-25 22:18:49.106810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9b0a95e82045'
down_revision: Union[str, None] = '362e0db184c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'books', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'user_id')
    # ### end Alembic commands ###
